spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: auth_user
    password: auth_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081

jwt:
  secret: f4A9Kx7pQzL3mN8vR2wY6bT1cE5jH0sD9gU4iO7aP3k=