

services:
  wallet-postgres:
    image: postgres:16
    container_name: wallet-postgres
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
    ports:
      - "5432:5432"
    volumes:
      - wallet_pgdata:/var/lib/postgresql/data

  auth-postgres:
   image: postgres:16
   container_name: auth-postgres
   environment:
    POSTGRES_DB: auth_db
    POSTGRES_USER: auth_user
    POSTGRES_PASSWORD: auth_pass
   ports:
    - "5433:5432"
   volumes:
    - auth_pgdata:/var/lib/postgresql/data

volumes:
  wallet_pgdata:
  auth_pgdata: